# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Al < Formula
  desc "Mac Toolchain Manager - trial/core lifecycle management"
  homepage "https://github.com/kkato1030/al"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kkato1030/al/releases/download/v0.2.1/al_darwin_amd64.tar.gz"
      sha256 "417a6fd085fdd85217f575a32b149e7fc6541bed687dd3d1e5ef7e3613b5cb31"

      def install
        bin.install "al"
      end
    end
    on_arm do
      url "https://github.com/kkato1030/al/releases/download/v0.2.1/al_darwin_arm64.tar.gz"
      sha256 "a20ffc535583b9ea66350d5d3f6f134b5ab1dc384dea6dd552baeef9552345bc"

      def install
        bin.install "al"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkato1030/al/releases/download/v0.2.1/al_linux_amd64.tar.gz"
        sha256 "8ec22f2f3290bfb30aaedac449adb7dad30c145a1b0d5eb0598c7223ca5d4c7f"

        def install
          bin.install "al"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkato1030/al/releases/download/v0.2.1/al_linux_arm64.tar.gz"
        sha256 "740486f268440a4eae512596d79c2ad9348dc87da3c2f3b68dc87618d1aa820a"

        def install
          bin.install "al"
        end
      end
    end
  end

  test do
    system "#{bin}/al --version"
  end
end
