# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Al < Formula
  desc "Mac Toolchain Manager - trial/core lifecycle management"
  homepage "https://github.com/kkato1030/al"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kkato1030/al/releases/download/v0.1.1/al_darwin_amd64.tar.gz"
      sha256 "73322c349d8e7da8db7da754baab2a327aad4b2cc73ab31d917e130cefb85761"

      def install
        bin.install "al"
      end
    end
    on_arm do
      url "https://github.com/kkato1030/al/releases/download/v0.1.1/al_darwin_arm64.tar.gz"
      sha256 "b721cdce0045905d0968ad9c5f8570e5ec9590b4e921759e0fa7567adc6fc12d"

      def install
        bin.install "al"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkato1030/al/releases/download/v0.1.1/al_linux_amd64.tar.gz"
        sha256 "a275c54af1a080996733edfbfd59ea798da954ba7697bf11c606d981f1cbafe4"

        def install
          bin.install "al"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkato1030/al/releases/download/v0.1.1/al_linux_arm64.tar.gz"
        sha256 "88798fd322ccf4c4c568e6f655070c122d8e8d7a41b894b1d7376482f936ee81"

        def install
          bin.install "al"
        end
      end
    end
  end

  test do
    system "#{bin}/al --version"
  end
end
