# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kit < Formula
  desc "Mac Toolchain Manager - trial/core lifecycle management"
  homepage "https://github.com/kkato1030/kit"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kkato1030/kit/releases/download/v0.1.0/kit_darwin_amd64.tar.gz"
      sha256 "5e411730b190ac0029231a74c181f3e97f3d6bb005c80b8e66fc399886051a88"

      def install
        bin.install "kit"
      end
    end
    on_arm do
      url "https://github.com/kkato1030/kit/releases/download/v0.1.0/kit_darwin_arm64.tar.gz"
      sha256 "59b257973e62ae57ee0d536d28cfc168ba3909e3831f7ada2ff7384165cb7faf"

      def install
        bin.install "kit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkato1030/kit/releases/download/v0.1.0/kit_linux_amd64.tar.gz"
        sha256 "034f5a36706492579b8b40765b2ddf5c23d221799b4e97d7d680c577b85e494c"

        def install
          bin.install "kit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkato1030/kit/releases/download/v0.1.0/kit_linux_arm64.tar.gz"
        sha256 "d1a8f715b919b02ce3e8b05e30931851df8f7ff5bb1a120368be3f4c79fcef38"

        def install
          bin.install "kit"
        end
      end
    end
  end

  test do
    system "#{bin}/kit --version"
  end
end
