# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sway < Formula
  desc "A CLI tool for managing tasks, contexts, and time tracking"
  homepage "https://github.com/kkato1030/sway-cli"
  version "0.1.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/kkato1030/sway-cli/releases/download/v0.1.4/sway_0.1.4_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "216505047d545d6a20d3841e1bff418b7522fa915d3b73520d06cbdf649756db"

    define_method(:install) do
      bin.install "sway"
    end
  end

  test do
    system "#{bin}/sway", "--version"
  end
end
