# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private_strategy"
class Sway < Formula
  desc "A CLI tool for managing tasks, contexts, and time tracking"
  homepage "https://github.com/kkato1030/sway-cli"
  version "0.20.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/kkato1030/sway-cli/releases/download/v0.20.0/sway_0.20.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryDownloadStrategy
    sha256 "001840868bb042ac797cbeaafbe59c3dead437dfa48b9ecc3ffa2fe786c38b43"

    define_method(:install) do
      bin.install "sway"
    end
  end

  test do
    system "#{bin}/sway", "--version"
  end
end
